export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_INCREMENT_ITEM = "BASKET_INCREMENT_ITEM";
export const BASKET_DECREMENT_ITEM = "BASKET_DECREMENT_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";